//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gurux.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gurux.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Updates.
        /// </summary>
        internal static string AvailableUpdatesTxt {
            get {
                return ResourceManager.GetString("AvailableUpdatesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes the dialog box without saving any changes you have made..
        /// </summary>
        internal static string CancelHelp {
            get {
                return ResourceManager.GetString("CancelHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelTxt {
            get {
                return ResourceManager.GetString("CancelTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string CopyTxt {
            get {
                return ResourceManager.GetString("CopyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Help topic is associated with this item..
        /// </summary>
        internal static string HelpNotAvailable {
            get {
                return ResourceManager.GetString("HelpNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copies files to the clipboard..
        /// </summary>
        internal static string LibraryCopyHelp {
            get {
                return ResourceManager.GetString("LibraryCopyHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows product and library versions..
        /// </summary>
        internal static string LibraryListHelp {
            get {
                return ResourceManager.GetString("LibraryListHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Versions.
        /// </summary>
        internal static string LibraryVersionsTxt {
            get {
                return ResourceManager.GetString("LibraryVersionsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameTxt {
            get {
                return ResourceManager.GetString("NameTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New updates available.
        /// </summary>
        internal static string NewProtocolsAvailableTxt {
            get {
                return ResourceManager.GetString("NewProtocolsAvailableTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are new updates available. Do you want to download them?.
        /// </summary>
        internal static string NewProtocolsDownloadTxt {
            get {
                return ResourceManager.GetString("NewProtocolsDownloadTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocols.
        /// </summary>
        internal static string ProtocolsTxt {
            get {
                return ResourceManager.GetString("ProtocolsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string VersionTxt {
            get {
                return ResourceManager.GetString("VersionTxt", resourceCulture);
            }
        }
    }
}
